Repository aas-core-works/aas-core-meta, pull requests merged in 2023-03, with the labels that each got.

#241 [v3.0] Fix typo in docstring of Administrative_information
  aas_core_meta/v3.py
Labels: V3.0

#243 [v3.0] Remove occurances of global references in docstring of `Reference`
  aas_core_meta/v3.py
Labels: V3.0

#260 Add a check for `entity_type` in invariant for `AASd-014`
  aas_core_meta/v3.py
Labels: V3.0

#263 [V3] Improve documentation
  aas_core_meta/v3.py
Labels: documentation, V3.0

#267 List all descendants of a cls in html-doc
  htmlgen/for_metamodel.py
  setup.py
Labels: V3.0, htmlgen
